### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [den10004/RegExp#1]
Добрый вечер. Благодарю за проделанную работу.
К сожалению, текущая реализация содержит ряд недостатков не позволяющих мне засчитать ее на данной итерации:

## Репозиторий
**Нужно исправить**: README файл должен содержать номер версии (ненулевой), ссылку на проект (github pages) и заголовок отражающий назначение проекта.

В дополнение к ссылкам из практики рекомендую почитать статью "Как написать хороший README?".

Ссылка на статью:
https://medium.com/astrolabe/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B8%D0%B9-readme-159f88076b26
Примеры шаблонов для README:
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2,
https://gist.github.com/fvcproductions/1bfc2d4aecb01a834b46

**Можно лучше**: Добавить .gitignore.
.gitignore должен содержать правила, исключающие попадание временных и\или системных файлов в репозиторий.
В случае если вы затрудняетесь с составлением списка базовых правил можете воспользоваться сервисом-генератором, например gitignore.io

### Email

Негативные:
`_@site.ru` - имя ящика не может состоять только из спецсимволов
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
`my---mail@site.ru` - адрес электронной почты, содержащий несколько символов '-' подряд является некорректным

### Номер телефона

**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.
```
+7925900-90-90
+792590090-90
+7 (925) 900-90-90
+7 (925) 9009090
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
+7 925 900-90-90
```
Также просьба зафиксировать код телефона +7, в соответствии с описанными корректными примерами в задании.

### Адрес сайта
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`http://www.ya.` - отсутствует доменная зона, точка на конце
`http://www`  - отсутствует доменное имя и зона
`http://.ru` - отсутствует доменное имя
`http:something.ru` - отсутствуют `//` после протокола
`zzz://ya.ru` - некорректный протокол. Допустимы только http\https
`http://google.ru:/path/to/deep` - отсутствует номер порта после символа `:`
`http://127.0.0..` - некорректный IP, точка на конце 
`http://127.0.0.1:8000/$ssss@#` - некорректный путь - разрешены только цифры, слеш и латинские буквы, решетка (#) на конце
`https://mysite.23` - tld не может состоять только из цифр)

**Можно лучше** следующие некорректные кейсы проходят валидаци
`http://www.google.ru/////// (в пути количество слешей подряд должно быть ограничено 1)

**Comment by zlocate** [comment]
Добрый вечер. Следующие кейсы требуют проработки:
### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию:
`some-extra-long-name@some.extra.long.domain.name`, `some@mail.yandex.ru` - адрес может содержать произвольное число поддоменов

### Адрес сайта
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`something.ru` - отсутствует протокол (http или https)

**Comment by zlocate** [comment]
Добрый вечер. Работа принята.

**Comment by den10004** [comment]
Исправлено.
